### ISSUE TITLE
link footer "ERDL Team" to "People" tab on Github

### ISSUE THREAD

**Issue by carlosparadis** [erdl/erdl.github.io#2]
https://github.com/orgs/erdl/people

Better than someone thinking localhost:4000 is the mastermind behind the organization :^). 

Also on the same commit, I think there is a minor typo on one of the sections on the menu:

"Data aquisition" (missing a c => acquisition).

**Comment by ryantanaka** [comment]
@carlosparadis, changes have been made and are now live on the site. Thanks for pointing out the typo.
Closing this issue.

**Comment by ryantanaka** [comment]
Making a few more changes...

**Comment by ryantanaka** [comment]
I needed to also rename the file since I renamed the url that calls the file. The typo was in 2 more places aside what you saw... now its live and running correctly.
